[Lift_Door]
CanHeal = FALSE
CanRepair = FALSE
CanDamage = FALSE
NeverDestroy = TRUE
ActivateTrigger = FALSE
TriggerClose = TRUE
RemainsOpen = TRUE
ForceMove = TRUE
Speed = 200.0f
MoveDelay = 1.0f
MoveDist = 100.0f
MoveDir = <0.0, 1.0, 0.0>
OpenWaitTime = 2.0f
CloseWaitTime = 2.0f
OpenSound = "Snd\Lifts\01start.wav"
CloseSound = "Snd\Lifts\01start.wav"
LoopSounds = TRUE

[Glass_Door]
CanHeal = FALSE
CanRepair = FALSE
CanDamage = TRUE
NeverDestroy = FALSE
ActivateTrigger = FALSE
GLASS_SMALL = TRUE
METAL_BIG = FALSE
HitPoints = 5
Armor = 5
MoveDist = 0
MoveDir = <0.0, 0.0, 0.0>
OpenWaitTime = 0
CloseWaitTime = 0

[Destructible_Door]
CanHeal = FALSE
CanRepair = FALSE
CanDamage = TRUE
NeverDestroy = FALSE
ActivateTrigger = FALSE
WOODCHIPS = TRUE
METAL_BIG = FALSE
HitPoints = 50
Armor = 5
MoveDist = 0
MoveDir = <0.0, 0.0, 0.0>
OpenWaitTime = 0
CloseWaitTime = 0

[MaskedMetal_Door]
CanHeal = FALSE
CanRepair = FALSE
CanDamage = TRUE
NeverDestroy = TRUE
ActivateTrigger = FALSE
METAL_BIG = TRUE
HitPoints = 5
Armor = 5
MoveDist = 0
MoveDir = <0.0, 0.0, 0.0>
OpenWaitTime = 0
CloseWaitTime = 0

