[Trigger___GIBTrigger_Torso]
Dims = <64.0, 64.0, 64.0>
NumberOfActivation = 10000
TriggerTouch = TRUE
MessageTouch = "hitnode torso_node; damage 10000"
AITriggerable = TRUE

[AmmoBox___AmmoPack]
Skin = "skins\props\ammopack.dtx"
Filename = "models\props\ammopack.abc"

[AmmoBox___AmmoBoxSkin2]
Skin = "skins\props\ammobox2.dtx"

[AmmoBox___AmmoBoxSkin3]
Skin = "skins\props\ammobox3.dtx"

[AICorporate___AIC_MaleLabTech]
DEditDims = "Models\Characters\malelabtech.abc"
CharacterType = "MaleLabTech"

[AICorporate___AIC_FemaleLabTech]
DEditDims = "Models\Characters\femalelabtech.abc"
CharacterType = "FemaleLabTech"

[AICorporate___AIC_Scientist]
DEditDims = "Models\Characters\scientist.abc"
CharacterType = "Scientist"

[AICorporate___AIC_Laboror]
DEditDims = "Models\Characters\laboror.abc"
CharacterType = "Laboror"

[AICorporate___AIC_MaleLabSynth]
DEditDims = "Models\Characters\malelabsynth.abc"
CharacterType = "MaleLabSynth"

[AICorporate___AIC_FemaleLabSynth]
DEditDims = "Models\Characters\femalelabsynth.abc"
CharacterType = "FemaleLabSynth"

[AICorporate___AIC_CombatSynth]
DEditDims = "Models\Characters\combatsynth.abc"
CharacterType = "CombatSynth"
AttributeTemplate = "CombatSynthAI"

[AICorporate___AIC_Dunya]
DEditDims = "Models\Characters\merc2.abc"
CharacterType = "Dunya"

[AICorporate___AIC_ApeSuit]
DEditDims = "Models\Characters\apesuit.abc"
CharacterType = "APESuit"

[AICorporate___AIC_Guard]
DEditDims = "Models\Characters\guard.abc"
CharacterType = "Guard"

[AICorporate___AIC_Officer]
DEditDims = "Models\Characters\officer.abc"
CharacterType = "Officer"

[AICorporate___AIC_Hazmat]
DEditDims = "Models\Characters\hazmat.abc"
CharacterType = "Hazmat"

[AICorporate___AIC_PulseRifleGuy2]
DEditDims = "Models\Characters\pulserifleguy2.abc"
CharacterType = "PulseRifleGuy2"

[AICorporate___AIC_Smuggler]
DEditDims = "Models\Characters\smuggler.abc"
CharacterType = "Smuggler"

[AICorporate___AIC_Tamiko]
DEditDims = "Models\Characters\tamiko.abc"
CharacterType = "Tamiko"

[AICorporate___AIC_Merc1]
DEditDims = "Models\Characters\merc1.abc"
CharacterType = "Merc1"

[AICorporate___AIC_Merc2]
DEditDims = "Models\Characters\merc2.abc"
CharacterType = "Merc2"

[AICorporate___AIC_Merc3]
DEditDims = "Models\Characters\merc3.abc"
CharacterType = "Merc3"

[AICorporate___AIC_Merc4]
DEditDims = "Models\Characters\merc4.abc"
CharacterType = "Merc4"

[AIExosuit___AIE_Exosuit]
DEditDims = "Models\Characters\exosuit.abc"
CharacterType = "Corporate_Exosuit"
AttributeTemplate = "BasicExosuit"

[AIMarine___AIM_Harris]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "Harris"

[AIMarine___AIM_Grenadier]
DEditDims = "Models\Characters\grenadier.abc"
CharacterType = "Grenadier"

[AIMarine___AIM_Obrian]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "Obrian"

[AIMarine___AIM_RailGunner]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "RailGunner"

[AIMarine___AIM_SmartGunner]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "SmartGunner"

[AIMarine___AIM_MiniGunner]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "MiniGunner"

[AIMarine___AIM_PulseRifleGuy]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "PulseRifleGuy"

[AIMarine___AIM_PulseRifleGirl]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "PulseRifleGirl"

[AIMarine___AIM_SADARGunner]
DEditDims = "Models\Characters\harris.abc"
CharacterType = "SADARGunner"

[AIMarine___AIM_Exosuit]
DEditDims = "Models\Characters\ExoSuit.abc"
CharacterType = "Marine_Exosuit"
AttributeTemplate = "BasicMarineExosuit"


[AIAlien___AIA_Facehugger]
DEditDims = "Models\Characters\facehugger.abc"
CharacterType = "Facehugger"
AttributeTemplate = "BasicFaceHugger"

[AIAlien___AIA_Chestburster]
DEditDims = "Models\Characters\chestburster.abc"
CharacterType = "Chestburster"
AttributeTemplate = "BasicChestBurster"

[AIAlien___AIA_Runner]
DEditDims = "Models\Characters\runner.abc"
CharacterType = "Runner"

[AIAlien___AIA_Drone]
DEditDims = "Models\Characters\drone.abc"
CharacterType = "Drone"

[AIAlien___AIA_Predalien]
DEditDims = "Models\Characters\predalien.abc"
CharacterType = "Predalien"

[AIAlien___AIA_Praetorian]
DEditDims = "Models\Characters\praetorian.abc"
CharacterType = "Praetorian"

[AIAlien___AIA_Queen]
DEditDims = "Models\Characters\queen.abc"
CharacterType = "Queen"
AttributeTemplate = "Queen"

[AIAlien___AIA_Emperess]
DEditDims = "Models\Characters\emperess.abc"
CharacterType = "Emperess"
AttributeTemplate = "Emperess"

[StoryObject___PDA]
Filename = "models\props\pda.abc"
Skin = "skins\props\pda.dtx"
Bitmap = "interface\statusbar\pda.pcx"
TextXOffset = 119
TextYOffset = 64
TextWidth = 403
Font = "PDA"
Sound = "PDA_Sound"

[StoryObject___MEMO]
Filename = "models\props\memo.abc"
Skin = "skins\props\memo.dtx"
Bitmap = "interface\statusbar\memo.pcx"
TextXOffset = 172
TextYOffset = 90
TextWidth = 292
Font = "MEMO"
Sound = "MEMO_Sound"

[StoryObject___PC]
Filename = "models\props\pc.abc"
Skin = "skins\props\pc.dtx"
Bitmap = "interface\statusbar\pc.pcx"
TextXOffset = 116
TextYOffset = 101
TextWidth = 330
Font = "PDA"
Sound = "PDA_Sound"


